import './js/menu-header/menu-header.js';
import './js/support/support.js';
import './js/home/modal-card';
import './js/home/render-books-list.js';
import './js/menu-header/switcher.js';
import './js/home/render-categories-list.js';
import './js/home/scroll-up.js';
import './js/menu-header/firebase-sing-up.js';
import './js/menu-header/firebase-sing-in.js';
